### ISSUE TITLE
Lots of good tidytext tutorials and material

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/course-site#152]
If I want to expand this. Also great for `css-model` as well.

https://juliasilge.com/blog/

**Comment by bensoltoff** [comment]
Relatedly, [Supervised Machine Learning for Text Analysis with R](https://smltar.com/) by Hvitfeldt and Silge

**Comment by bensoltoff** [comment]
Essentially, is it time to do a revamp of the text analysis unit? It was originally constructed in 2016 and relies a lot on the procedures outlined in [Text Mining with R](https://www.tidytextmining.com/). I've added to it since then and adapted some new procedures/examples. Are the techniques/implementations out of date? Should there be additional methods? Anything to cut to make room for additional topics?

Also I need to develop some in-class practice exercises for supervised/unsupervised text analysis. Right now it is pure lecture and that is BORING

**Comment by djanvier** [comment]
Hiya, sorry I'm getting to this so late! Are you trying to add these examples to the "Syllabus" page or to the actual lecture notes for text analysis? I do agree that it's time to revamp the text analysis unit, but I think it's a lot more work than this issue entails. I'm currently going through all the lessons and examples for the text analysis unit, as well as the resources you provided me, and can provide more concrete notes/thoughts about the unit later today

**Comment by djanvier** [comment]
Also wondering if you want me to abstain from any examples that uses `tidymodels` since weren't able to fully incorporate it this time around

**Comment by bensoltoff** [comment]
At this point there is not any time to modify the unit for this week. Any revisions will be folded into the winter quarter when I plan to make the switch to tidymodels. So it is fine to use examples which leverage that package.

My current thoughts are that the general topics this week are still appropriate, but the methodology needs some updating and exercises could be potentially revised. Right not that looks like

- Streamlining the [Harry Potter exercise](https://cfss.uchicago.edu/notes/harry-potter-exercise/) or replacing it entirely. I just never have enough time to work through the set of exercises during class. That, or I need to cut back on more of the lecture on that day which relies on more student prep ahead of time. That seems less likely
- Supervised classification - a (relatively) straightforward tutorial/introduction to classification using `tidytext`/`tidymodels` and explaining the basics of things such as tokenization, stemming, etc. Word embeddings would be nice, but not essential (also not much time)
- Unsupervised learning - the topic modeling that is demoed now, but LDA is a pretty old technique. I'm not sure it really fits with more modern approaches such as [structural topic models](https://github.com/bstewart/stm).
- Exercises for supervised classification and unsupervised learning. I need to convert that unit so the tutorials are read in advance, then the bulk of class is spent practicing applying those methods on a different data set.

And as I write this all out, I realize it is quite a large task. A decent starting point could be revising the current supervised classification example to use a `tidymodels` approach a la [Supervised Machine Learning](https://smltar.com/). This would assume students have already been introduced to tidymodels and the basic `workflow()`, recipes, etc. So it focuses more on incorporating text data as the features rather than standard numeric data.

**Comment by bensoltoff** [comment]
Some of this has been done already. Fold remaining elements into #324.
