### ISSUE TITLE
Add list of resources for underrepresented groups in programming

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/course-site#181]

**Comment by Seagullible** [comment]
I can take a look at this.

**Comment by bensoltoff** [comment]
Originally sourced from @civicangela

* https://twitter.com/r_lgbtq
* https://twitter.com/gaytascience
* http://bit.ly/rladies-slack
* https://twitter.com/RLadiesRemote
* https://rladiesinvite.herokuapp.com/
* https://www.meetup.com/People-of-Color-Code/
* https://forwards.github.io/
* https://github.com/RConsortium/RCDI-WG

**Comment by bensoltoff** [comment]
Closed by #263
