### ISSUE TITLE
Demonstrate iterative operations for APIs and web scraping

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/course-site#264]
[Rochelle](https://plsc-31101.github.io/course/collecting-data-from-the-web.html#iteration-through-results-pager) has a simple example using the NYTimes API. Would also be a good entry point for the `polite` package.

See #207

**Comment by deblnia** [comment]
I like this! Would add maybe an example using `RSelenium` or something to that effect for JS tables.
