### ISSUE TITLE
Update Data Wrangling Exercises to Match Data in `rcfss` 

### ISSUE THREAD

**Issue by deblnia** [uc-cfss/course-site#269]
Someone pointed this out during in-class exercises on Tuesday -- if I'm remembering correctly it's a relatively small fix, so I can definitely take it on! 
Just make an issue so we're all on the same page + so I don't forget 😄

**Comment by bensoltoff** [comment]
Were these the exercises with scorecard or something else? `rcfss` on the server was out of date hence the different results compared to the website. But I already got the server updated. Was this a different set of exercises?
