### ISSUE TITLE
HW04

### ISSUE THREAD

**Issue by bensoltoff** [uc-cfss/course-site#68]
Add tests for the Pythagorean function so that students prove the function performs as expected

**Comment by bensoltoff** [comment]
Need to do, but have to avoid giving specific unit test if I let them open-ended design the function name and arguments

**Comment by deblnia** [comment]
If we give a function stub, we can use `testthat` -- as noted, trickier with open-ended design.

**Comment by bensoltoff** [comment]
Yeah, that's always been my concern with unit testing in this course. I know that's far more common in the CS 120s and other explicit CS courses but I've always preferred developing more open-ended exercises since that is far more similar to the situations in which students will find themselves. Plus selecting appropriate arguments is part of the challenge depending on how they structure the body of the function.

**Comment by deblnia** [comment]
Last question I promise: how wedded are you to the pythagorean function? Could we do something more tidyverse-centric? (i.e. a function to [generate a bunch of EDA plots](https://aosmith.rbind.io/2018/08/20/automating-exploratory-plots/) or do some custom / repetitive grouping/summarizing)

**Comment by bensoltoff** [comment]
That depends on the format of the function. Students need to be able to write a function; define an appropriate set of arguments; construct the body using some combination of conditional expressions (this is really the value of the pythagorean function since there are potentially multiple conditions to evaluate and the order of operations matters).

It cannot require [non-standard evaluation](https://dplyr.tidyverse.org/articles/programming.html) as that is beyond the scope of this class. This is why I don't usually demonstrate how to write functions incorporating `dplyr` or `ggplot2` operations. Again, this is something I would cover in MCFSS but for pedagogical reasons I leave out of CFSS. The EDA example you linked to does not require those operations, though it incorporates the concept of `.data` and also does not use any conditional operations.

If you want to prototype an example function that you think meets these requirements, I'd be happy to take a look at it.
